package sessionoverride

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/devlikebear/tars/internal/session"
)

const (
	sharedSettingsName = "settings.json"
	localSettingsName  = "settings.local.json"
	settingsDirName    = ".tars"
)

// Load reads session-cwd override files (`<cwd>/.tars/settings.json` and
// `<cwd>/.tars/settings.local.json`) if they exist. A missing file is not
// an error — both return values are nil in that case. JSON parse failures
// abort the load with a descriptive error; schema violations (blocked or
// unknown fields) are returned as diagnostics with the offending field
// dropped from the parsed Override.
func Load(cwd string) (shared, local *Override, diagnostics []Diagnostic, err error) {
	cwd = strings.TrimSpace(cwd)
	if cwd == "" {
		return nil, nil, nil, nil
	}
	info, statErr := os.Stat(filepath.Join(cwd, settingsDirName))
	if statErr != nil {
		if errors.Is(statErr, os.ErrNotExist) {
			return nil, nil, nil, nil
		}
		return nil, nil, nil, fmt.Errorf("stat %s: %w", filepath.Join(cwd, settingsDirName), statErr)
	}
	if !info.IsDir() {
		return nil, nil, nil, nil
	}

	sharedPath := filepath.Join(cwd, settingsDirName, sharedSettingsName)
	localPath := filepath.Join(cwd, settingsDirName, localSettingsName)

	shared, sharedDiags, err := loadFile(sharedPath)
	if err != nil {
		return nil, nil, nil, err
	}
	diagnostics = append(diagnostics, sharedDiags...)

	local, localDiags, err := loadFile(localPath)
	if err != nil {
		return nil, nil, diagnostics, err
	}
	diagnostics = append(diagnostics, localDiags...)

	return shared, local, diagnostics, nil
}

// loadFile parses a single override file at path. Returns nil Override
// (no error) when the file does not exist.
func loadFile(path string) (*Override, []Diagnostic, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil, nil
		}
		return nil, nil, fmt.Errorf("read %s: %w", path, err)
	}
	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		return nil, nil, fmt.Errorf("parse %s: %w", path, err)
	}

	override := &Override{Presence: map[string]bool{}}
	var diags []Diagnostic

	for key, value := range top {
		key = strings.TrimSpace(key)
		switch {
		case key == "":
			continue
		case isBlockedTopLevel(key):
			diags = append(diags, Diagnostic{
				Path:     key,
				Severity: SeverityError,
				Message:  fmt.Sprintf("field %q is not permitted in session-cwd override files; ignoring", key),
				File:     path,
			})
		case isAllowedTopLevel(key):
			d, err := assignTopLevel(override, key, value, path)
			if err != nil {
				return nil, nil, fmt.Errorf("decode %s in %s: %w", key, path, err)
			}
			diags = append(diags, d...)
		default:
			diags = append(diags, Diagnostic{
				Path:     key,
				Severity: SeverityWarn,
				Message:  fmt.Sprintf("unknown field %q ignored", key),
				File:     path,
			})
		}
	}

	return override, diags, nil
}

func isAllowedTopLevel(key string) bool {
	_, ok := AllowedTopLevelFields[key]
	return ok
}

func isBlockedTopLevel(key string) bool {
	_, ok := BlockedTopLevelFields[key]
	return ok
}

// assignTopLevel decodes one top-level allowed field into the Override.
// Returns any diagnostics generated by nested validation (currently only
// `tool_config` has nested schema enforcement).
func assignTopLevel(o *Override, key string, raw json.RawMessage, file string) ([]Diagnostic, error) {
	switch key {
	case "prompt_override":
		var s string
		if err := json.Unmarshal(raw, &s); err != nil {
			return nil, err
		}
		o.PromptOverride = &s
		o.Presence["prompt_override"] = true
		return nil, nil

	case "model_tier_override":
		var s string
		if err := json.Unmarshal(raw, &s); err != nil {
			return nil, err
		}
		o.ModelTierOverride = &s
		o.Presence["model_tier_override"] = true
		return nil, nil

	case "claude_code_cli_permission_mode":
		var s string
		if err := json.Unmarshal(raw, &s); err != nil {
			return nil, err
		}
		o.ClaudeCodeCLIPermissionMode = &s
		o.Presence["claude_code_cli_permission_mode"] = true
		return nil, nil

	case "mcp_servers_extra":
		var entries []MCPServerExtra
		if err := json.Unmarshal(raw, &entries); err != nil {
			return nil, err
		}
		o.MCPServersExtra = entries
		o.Presence["mcp_servers_extra"] = true
		return nil, nil

	case "tool_config":
		return assignToolConfig(o, raw, file)
	}
	return nil, fmt.Errorf("internal: missing decoder for allowed key %q", key)
}

func assignToolConfig(o *Override, raw json.RawMessage, file string) ([]Diagnostic, error) {
	var nested map[string]json.RawMessage
	if err := json.Unmarshal(raw, &nested); err != nil {
		return nil, err
	}
	tc := &session.SessionToolConfig{}
	var diags []Diagnostic

	for key, value := range nested {
		key = strings.TrimSpace(key)
		if key == "" {
			continue
		}
		if _, ok := AllowedToolConfigFields[key]; !ok {
			diags = append(diags, Diagnostic{
				Path:     "tool_config." + key,
				Severity: SeverityWarn,
				Message:  fmt.Sprintf("unknown tool_config subfield %q ignored", key),
				File:     file,
			})
			continue
		}
		if err := decodeToolConfigField(tc, key, value); err != nil {
			return nil, fmt.Errorf("decode tool_config.%s: %w", key, err)
		}
		o.Presence["tool_config."+key] = true
	}

	o.ToolConfig = tc
	return diags, nil
}

func decodeToolConfigField(tc *session.SessionToolConfig, key string, raw json.RawMessage) error {
	switch key {
	case "tools_enabled":
		return json.Unmarshal(raw, &tc.ToolsEnabled)
	case "tools_custom":
		return json.Unmarshal(raw, &tc.ToolsCustom)
	case "tools_disabled":
		return json.Unmarshal(raw, &tc.ToolsDisabled)
	case "tools_allow_groups":
		return json.Unmarshal(raw, &tc.ToolsAllowGroups)
	case "tools_deny_groups":
		return json.Unmarshal(raw, &tc.ToolsDenyGroups)
	case "skills_enabled":
		return json.Unmarshal(raw, &tc.SkillsEnabled)
	case "skills_custom":
		return json.Unmarshal(raw, &tc.SkillsCustom)
	case "commands_enabled":
		return json.Unmarshal(raw, &tc.CommandsEnabled)
	case "commands_custom":
		return json.Unmarshal(raw, &tc.CommandsCustom)
	case "mcp_enabled":
		return json.Unmarshal(raw, &tc.MCPEnabled)
	case "mcp_custom":
		return json.Unmarshal(raw, &tc.MCPCustom)
	}
	return fmt.Errorf("internal: missing decoder for tool_config.%s", key)
}
