package onboarding

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteSkeletonConfig writes the config a fresh install starts from: no LLM
// providers or tiers, so the server boots in setup-only mode and the wizard
// at /console fills them in. Auth is off for loopback use, because a fresh
// install has no token the wizard could send to /v1/admin/*.
//
// `tars init` writes it, and so does `tars serve` the first time it starts
// on a loopback address without a config file.
func WriteSkeletonConfig(configPath, workspaceDir, apiAddr string) error {
	if err := os.MkdirAll(filepath.Dir(configPath), 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	if err := os.WriteFile(configPath, []byte(SkeletonConfig(workspaceDir, apiAddr)), 0o644); err != nil {
		return fmt.Errorf("write onboarding config: %w", err)
	}
	return nil
}

// SkeletonConfig renders the file WriteSkeletonConfig writes.
func SkeletonConfig(workspaceDir, apiAddr string) string {
	return strings.TrimSpace(fmt.Sprintf(`
# TARS skeleton config generated by "tars init" (or the first "tars serve").
# The setup wizard at /console fills in llm_providers and llm_tiers.
# Re-run "tars init reset" to start the wizard from scratch.

runtime:
  workspace_dir: %s

# Local-only starter auth. Change to "required" before exposing beyond localhost.
api:
  auth_mode: off
  allow_insecure_local_auth: true
# Note: api.addr is not a config field; the listen address is passed via
# --api-addr to "tars serve" (baked into the LaunchAgent plist by init,
# or into the detached spawn). This file records it as a comment for
# operators: %s

agentruntime:
  enabled: true
`+"\n", workspaceDir, apiAddr))
}
