package main

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/devlikebear/tars/internal/config"
)

// swapInitResetHooks swaps both the orchestrator hooks (server start /
// healthz / browser) and the confirmation prompt for the reset flow.
// All reset tests run with --yes implicitly via this swap unless they
// explicitly test the prompt.
func swapInitResetHooks(t *testing.T, state *initMockState) {
	t.Helper()
	swapInitHooks(t, state)
	prevTimestamp := initResetTimestamp
	initResetTimestamp = func() string { return "20260101-000000" }
	t.Cleanup(func() { initResetTimestamp = prevTimestamp })
}

func writeFakeOnboardingConfig(t *testing.T, workspaceAbs string) {
	t.Helper()
	cfgPath := config.FixedConfigPath()
	if err := os.MkdirAll(filepath.Dir(cfgPath), 0o755); err != nil {
		t.Fatalf("mkdir config: %v", err)
	}
	contents := strings.TrimSpace(`
runtime:
  workspace_dir: ` + workspaceAbs + `
api:
  auth_mode: off
  allow_insecure_local_auth: true
agentruntime:
  enabled: true
llm_providers:
  default:
    kind: openai
    auth_mode: api-key
    api_key: ${OPENAI_API_KEY}
llm_tiers:
  heavy: {provider: default, model: gpt-4o-mini}
  standard: {provider: default, model: gpt-4o-mini}
  light: {provider: default, model: gpt-4o-mini}
llm_default_tier: standard
`) + "\n"
	if err := os.WriteFile(cfgPath, []byte(contents), 0o644); err != nil {
		t.Fatalf("write config: %v", err)
	}
}

func TestInitReset_BacksUpConfigAndRegeneratesSkeleton(t *testing.T) {
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	t.Setenv("TARS_PLUGINS_BUNDLED_DIR", filepath.Join(t.TempDir(), "no-such"))

	wsAbs := filepath.Join(fakeHome, ".tars", "workspace")
	if err := os.MkdirAll(wsAbs, 0o755); err != nil {
		t.Fatalf("mkdir ws: %v", err)
	}
	writeFakeOnboardingConfig(t, wsAbs)
	originalConfigBytes, _ := os.ReadFile(config.FixedConfigPath())

	state := &initMockState{startResult: initStartResult{mode: "detached"}}
	swapInitResetHooks(t, state)
	initRuntimeGOOS = "linux"

	var stdout strings.Builder
	cmd := newRootCommand(strings.NewReader(""), &stdout, io.Discard)
	cmd.SetArgs([]string{"init", "reset", "--yes", "--no-browser"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init reset: %v", err)
	}

	// Backup must exist with original payload.
	bakPath := config.FixedConfigPath() + ".bak"
	bakBytes, err := os.ReadFile(bakPath)
	if err != nil {
		t.Fatalf("read backup: %v", err)
	}
	if string(bakBytes) != string(originalConfigBytes) {
		t.Fatalf("backup did not match original payload\n--- original ---\n%s\n--- backup ---\n%s", originalConfigBytes, bakBytes)
	}

	// New config is the wizard skeleton.
	newBytes, _ := os.ReadFile(config.FixedConfigPath())
	if !strings.Contains(string(newBytes), "TARS skeleton config generated by") {
		t.Fatalf("expected fresh skeleton, got:\n%s", string(newBytes))
	}
	if strings.Contains(string(newBytes), "${OPENAI_API_KEY}") {
		t.Fatalf("skeleton must not carry the previous LLM section, got:\n%s", string(newBytes))
	}

	// Workspace preserved.
	if _, err := os.Stat(wsAbs); err != nil {
		t.Fatalf("expected workspace preserved, got err=%v", err)
	}

	// Orchestrator dispatched.
	if len(state.startCalls) != 1 {
		t.Fatalf("expected server start call, got %d", len(state.startCalls))
	}
	if state.healthBaseURL == "" {
		t.Fatalf("expected health probe to run")
	}
}

func TestInitReset_WipeWorkspaceRenamesNotDeletes(t *testing.T) {
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	t.Setenv("TARS_PLUGINS_BUNDLED_DIR", filepath.Join(t.TempDir(), "no-such"))

	wsAbs := filepath.Join(fakeHome, ".tars", "workspace")
	if err := os.MkdirAll(wsAbs, 0o755); err != nil {
		t.Fatalf("mkdir ws: %v", err)
	}
	sentinel := filepath.Join(wsAbs, "session.txt")
	if err := os.WriteFile(sentinel, []byte("user data"), 0o644); err != nil {
		t.Fatalf("write sentinel: %v", err)
	}
	writeFakeOnboardingConfig(t, wsAbs)

	state := &initMockState{startResult: initStartResult{mode: "detached"}}
	swapInitResetHooks(t, state)
	initRuntimeGOOS = "linux"

	var stdout strings.Builder
	cmd := newRootCommand(strings.NewReader(""), &stdout, io.Discard)
	cmd.SetArgs([]string{"init", "reset", "--yes", "--wipe-workspace", "--no-browser"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init reset --wipe-workspace: %v", err)
	}

	// Original workspace is gone, but the .bak.<timestamp> directory
	// must contain the sentinel — proves rename, not delete.
	bakWS := wsAbs + ".bak.20260101-000000"
	bakSentinel := filepath.Join(bakWS, "session.txt")
	data, err := os.ReadFile(bakSentinel)
	if err != nil {
		t.Fatalf("expected sentinel preserved in %s, got err=%v", bakWS, err)
	}
	if string(data) != "user data" {
		t.Fatalf("sentinel payload corrupted, got %q", string(data))
	}
	// The fresh workspace exists (re-scaffolded) — must be a different
	// inode from the .bak one. Just check it exists.
	if _, err := os.Stat(wsAbs); err != nil {
		t.Fatalf("expected fresh workspace re-scaffolded, got err=%v", err)
	}
}

func TestInitReset_RequiresConfirmationByDefault(t *testing.T) {
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	t.Setenv("TARS_PLUGINS_BUNDLED_DIR", filepath.Join(t.TempDir(), "no-such"))
	wsAbs := filepath.Join(fakeHome, ".tars", "workspace")
	_ = os.MkdirAll(wsAbs, 0o755)
	writeFakeOnboardingConfig(t, wsAbs)

	state := &initMockState{}
	swapInitResetHooks(t, state)
	initRuntimeGOOS = "linux"

	// Pipe an empty answer (just newline) — should be treated as "no".
	stdin := strings.NewReader("\n")
	var stdout strings.Builder
	cmd := newRootCommand(stdin, &stdout, io.Discard)
	cmd.SetArgs([]string{"init", "reset", "--no-browser"})
	err := cmd.Execute()
	if err == nil {
		t.Fatal("expected error when user declines prompt")
	}
	if !strings.Contains(err.Error(), "aborted") {
		t.Fatalf("expected 'aborted by user' error, got: %v", err)
	}
	if len(state.startCalls) != 0 {
		t.Fatalf("expected no orchestration after decline, got %d", len(state.startCalls))
	}
	// Config and backup must NOT have been touched.
	if _, err := os.Stat(config.FixedConfigPath() + ".bak"); err == nil {
		t.Fatal("expected no backup on declined prompt")
	}
}

func TestInitReset_YesAcceptsUppercase(t *testing.T) {
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	t.Setenv("TARS_PLUGINS_BUNDLED_DIR", filepath.Join(t.TempDir(), "no-such"))
	wsAbs := filepath.Join(fakeHome, ".tars", "workspace")
	_ = os.MkdirAll(wsAbs, 0o755)
	writeFakeOnboardingConfig(t, wsAbs)

	state := &initMockState{startResult: initStartResult{mode: "detached"}}
	swapInitResetHooks(t, state)
	initRuntimeGOOS = "linux"

	stdin := strings.NewReader("Y\n")
	var stdout strings.Builder
	cmd := newRootCommand(stdin, &stdout, io.Discard)
	cmd.SetArgs([]string{"init", "reset", "--no-browser"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init reset (Y): %v", err)
	}
	if len(state.startCalls) != 1 {
		t.Fatalf("expected start call after Y, got %d", len(state.startCalls))
	}
}

func TestInitReset_PortInheritsFromExistingPlist(t *testing.T) {
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	t.Setenv("TARS_PLUGINS_BUNDLED_DIR", filepath.Join(t.TempDir(), "no-such"))
	wsAbs := filepath.Join(fakeHome, ".tars", "workspace")
	_ = os.MkdirAll(wsAbs, 0o755)
	writeFakeOnboardingConfig(t, wsAbs)

	// Stage a plist that bakes --api-addr 127.0.0.1:43187 into the
	// ProgramArguments. Reset should reuse that addr instead of
	// auto-picking a different port.
	plistDir := filepath.Join(fakeHome, "Library", "LaunchAgents")
	_ = os.MkdirAll(plistDir, 0o755)
	plistPath := filepath.Join(plistDir, "io.tars.server.plist")
	plistBody := `<?xml version="1.0"?>
<plist version="1.0">
<dict>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/tars</string>
    <string>serve</string>
    <string>--config</string>
    <string>/tmp/tars-config.yaml</string>
    <string>--api-addr</string>
    <string>127.0.0.1:43187</string>
  </array>
</dict>
</plist>`
	if err := os.WriteFile(plistPath, []byte(plistBody), 0o644); err != nil {
		t.Fatalf("write plist: %v", err)
	}

	state := &initMockState{startResult: initStartResult{mode: "detached"}}
	swapInitResetHooks(t, state)
	initRuntimeGOOS = "linux" // skip launchd interaction; just check the addr threaded through

	var stdout strings.Builder
	cmd := newRootCommand(strings.NewReader(""), &stdout, io.Discard)
	cmd.SetArgs([]string{"init", "reset", "--yes", "--no-browser"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init reset: %v", err)
	}

	if len(state.startCalls) != 1 {
		t.Fatalf("expected 1 start call, got %d", len(state.startCalls))
	}
	if state.startCalls[0].apiAddr != "127.0.0.1:43187" {
		t.Fatalf("expected port inherited from plist, got %q", state.startCalls[0].apiAddr)
	}
}

func TestInitReset_ExplicitPortOverridesPlistInheritance(t *testing.T) {
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	t.Setenv("TARS_PLUGINS_BUNDLED_DIR", filepath.Join(t.TempDir(), "no-such"))
	wsAbs := filepath.Join(fakeHome, ".tars", "workspace")
	_ = os.MkdirAll(wsAbs, 0o755)
	writeFakeOnboardingConfig(t, wsAbs)

	plistDir := filepath.Join(fakeHome, "Library", "LaunchAgents")
	_ = os.MkdirAll(plistDir, 0o755)
	if err := os.WriteFile(filepath.Join(plistDir, "io.tars.server.plist"),
		[]byte(`<plist><dict><key>ProgramArguments</key><array><string>--api-addr</string><string>127.0.0.1:43187</string></array></dict></plist>`),
		0o644); err != nil {
		t.Fatalf("write plist: %v", err)
	}

	state := &initMockState{startResult: initStartResult{mode: "detached"}}
	swapInitResetHooks(t, state)
	initRuntimeGOOS = "linux"

	var stdout strings.Builder
	cmd := newRootCommand(strings.NewReader(""), &stdout, io.Discard)
	cmd.SetArgs([]string{"init", "reset", "--yes", "--no-browser", "--port", "43195"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init reset: %v", err)
	}
	if state.startCalls[0].apiAddr != "127.0.0.1:43195" {
		t.Fatalf("expected explicit --port to win, got %q", state.startCalls[0].apiAddr)
	}
}

func TestInitReset_NoConfigStillProceeds(t *testing.T) {
	// Resetting from a totally empty ~/.tars (no config to back up)
	// must not error — it just writes a fresh skeleton and starts the
	// server. Useful for users who manually deleted ~/.tars/config.
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	t.Setenv("TARS_PLUGINS_BUNDLED_DIR", filepath.Join(t.TempDir(), "no-such"))

	state := &initMockState{startResult: initStartResult{mode: "detached"}}
	swapInitResetHooks(t, state)
	initRuntimeGOOS = "linux"

	var stdout strings.Builder
	cmd := newRootCommand(strings.NewReader(""), &stdout, io.Discard)
	cmd.SetArgs([]string{"init", "reset", "--yes", "--no-browser"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init reset (no existing config): %v", err)
	}
	if _, err := os.Stat(config.FixedConfigPath()); err != nil {
		t.Fatalf("expected fresh skeleton written, got err=%v", err)
	}
	if _, err := os.Stat(config.FixedConfigPath() + ".bak"); err == nil {
		t.Fatal("expected no backup when there was nothing to back up")
	}
	if len(state.startCalls) != 1 {
		t.Fatalf("expected server start, got %d calls", len(state.startCalls))
	}
}

func TestReadExistingAPIAddrFromPlist_ParsesProgramArguments(t *testing.T) {
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	plistDir := filepath.Join(fakeHome, "Library", "LaunchAgents")
	_ = os.MkdirAll(plistDir, 0o755)
	plistPath := filepath.Join(plistDir, "io.tars.server.plist")
	body := `<plist><dict><key>ProgramArguments</key><array>
		<string>/bin/tars</string>
		<string>serve</string>
		<string>--api-addr</string>
		<string>127.0.0.1:43182</string>
	</array></dict></plist>`
	if err := os.WriteFile(plistPath, []byte(body), 0o644); err != nil {
		t.Fatalf("write plist: %v", err)
	}
	addr, ok := readExistingAPIAddrFromPlist()
	if !ok || addr != "127.0.0.1:43182" {
		t.Fatalf("expected 127.0.0.1:43182, got addr=%q ok=%v", addr, ok)
	}
}

func TestReadExistingAPIAddrFromPlist_NoFlagReturnsFalse(t *testing.T) {
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	plistDir := filepath.Join(fakeHome, "Library", "LaunchAgents")
	_ = os.MkdirAll(plistDir, 0o755)
	if err := os.WriteFile(filepath.Join(plistDir, "io.tars.server.plist"),
		[]byte(`<plist><dict><key>ProgramArguments</key><array><string>/bin/tars</string><string>serve</string></array></dict></plist>`),
		0o644); err != nil {
		t.Fatalf("write plist: %v", err)
	}
	if addr, ok := readExistingAPIAddrFromPlist(); ok {
		t.Fatalf("expected ok=false when --api-addr absent, got addr=%q", addr)
	}
}

func TestReadExistingAPIAddrFromPlist_MissingFileReturnsFalse(t *testing.T) {
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)
	if addr, ok := readExistingAPIAddrFromPlist(); ok {
		t.Fatalf("expected ok=false when plist missing, got addr=%q", addr)
	}
}

func TestPickInitResetAPIAddr_PriorityOrder(t *testing.T) {
	cases := []struct {
		name string
		opts initResetOptions
		prev string
		want string
	}{
		{"explicit api-addr wins", initResetOptions{apiAddr: "127.0.0.1:55555"}, "127.0.0.1:43187", "127.0.0.1:55555"},
		{"port wins over prev", initResetOptions{port: 43195}, "127.0.0.1:43187", "127.0.0.1:43195"},
		{"prev plist used when nothing explicit", initResetOptions{}, "127.0.0.1:43187", "127.0.0.1:43187"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := pickInitResetAPIAddr(tc.opts, tc.prev)
			if err != nil {
				t.Fatalf("err: %v", err)
			}
			if got != tc.want {
				t.Fatalf("expected %q, got %q", tc.want, got)
			}
		})
	}
}

func TestRunInitResetCommand_CallsRunnerThroughCobra(t *testing.T) {
	// Confirms `tars onboard reset` (alias) dispatches to the same
	// runner. Uses a minimal stub via initResetRunner.
	fakeHome := t.TempDir()
	t.Setenv("HOME", fakeHome)

	called := false
	prev := initResetRunner
	initResetRunner = func(_ context.Context, _ initResetOptions, _ io.Reader, _, _ io.Writer) error {
		called = true
		return nil
	}
	t.Cleanup(func() { initResetRunner = prev })

	cmd := newRootCommand(strings.NewReader(""), io.Discard, io.Discard)
	cmd.SetArgs([]string{"onboard", "reset", "--yes"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("onboard reset: %v", err)
	}
	if !called {
		t.Fatal("expected onboard reset to dispatch to initResetRunner")
	}
}
